// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOIgaKvncfRdXVJsJsHdq16L3nKrjC1_8',
    appId: '1:910715343608:web:885e64f1eaefcf3ebae10d',
    messagingSenderId: '910715343608',
    projectId: 'taskmanagement-e92e4',
    authDomain: 'taskmanagement-e92e4.firebaseapp.com',
    storageBucket: 'taskmanagement-e92e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBecW0fZsTOzeeVryriIzo3Sz5TuJGEcy4',
    appId: '1:910715343608:android:2322216b8dacc304bae10d',
    messagingSenderId: '910715343608',
    projectId: 'taskmanagement-e92e4',
    storageBucket: 'taskmanagement-e92e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq1Tk-sqmW57nY4VQdjrd2AVXjrdEWOa4',
    appId: '1:910715343608:ios:9014073d5bea3008bae10d',
    messagingSenderId: '910715343608',
    projectId: 'taskmanagement-e92e4',
    storageBucket: 'taskmanagement-e92e4.firebasestorage.app',
    iosBundleId: 'com.example.taskMgmt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq1Tk-sqmW57nY4VQdjrd2AVXjrdEWOa4',
    appId: '1:910715343608:ios:9014073d5bea3008bae10d',
    messagingSenderId: '910715343608',
    projectId: 'taskmanagement-e92e4',
    storageBucket: 'taskmanagement-e92e4.firebasestorage.app',
    iosBundleId: 'com.example.taskMgmt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOIgaKvncfRdXVJsJsHdq16L3nKrjC1_8',
    appId: '1:910715343608:web:7b14171a20de6eb5bae10d',
    messagingSenderId: '910715343608',
    projectId: 'taskmanagement-e92e4',
    authDomain: 'taskmanagement-e92e4.firebaseapp.com',
    storageBucket: 'taskmanagement-e92e4.firebasestorage.app',
  );
}
